# Generated by Django 5.2.6 on 2025-09-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
